const SHOW_LOGIN_POPUP = "SHOW_LOGIN_POPUP";
const CLOSE_LOGIN_POPUP = "CLOSE_LOGIN_POPUP";

const SHOW_REGISTER_POPUP = "SHOW_REGISTER_POPUP";
const CLOSE_REGISTER_POPUP = "CLOSE_REGISTER_POPUP";

export {
  SHOW_LOGIN_POPUP,
  CLOSE_LOGIN_POPUP,
  SHOW_REGISTER_POPUP,
  CLOSE_REGISTER_POPUP,
};
